import {
  ArrowDownUp,
  BadgeCheck,
  ChartNoAxesCombined,
  CircleUserRound,
  ClipboardList,
  DatabaseZap,
  Files,
  FolderKanban,
  Gavel,
  HandCoins,
  LayoutDashboard,
  Megaphone,
  Scale,
  SearchCheck,
  ShieldCheck,
  SlidersHorizontal,
  WalletCards,
} from "lucide-react";

export const RESEARCH_FUND_PAGE_ICONS = Object.freeze({
  dashboard: LayoutDashboard,
  researchDashboard: ChartNoAxesCombined,
  profile: CircleUserRound,
  researchFund: HandCoins,
  promotionFund: HandCoins,
  applications: ClipboardList,
  adminApplications: Files,
  receivedFunds: WalletCards,
  approvalRecords: BadgeCheck,
  announcements: Megaphone,
  projects: FolderKanban,
  departmentReview: Gavel,
  researchSearch: SearchCheck,
  scopusBenchmark: Scale,
  fundSettings: SlidersHorizontal,
  importExport: ArrowDownUp,
  academicImports: DatabaseZap,
  accessControl: ShieldCheck,
});

export const MEMBER_MENU_PRESENTATION = Object.freeze({
  profile: { icon: RESEARCH_FUND_PAGE_ICONS.profile, tone: "indigo" },
  "research-fund": { icon: RESEARCH_FUND_PAGE_ICONS.researchFund, tone: "emerald" },
  "promotion-fund": { icon: RESEARCH_FUND_PAGE_ICONS.promotionFund, tone: "amber" },
  applications: { icon: RESEARCH_FUND_PAGE_ICONS.applications, tone: "sky" },
  "received-funds": { icon: RESEARCH_FUND_PAGE_ICONS.receivedFunds, tone: "teal" },
  "approval-records": { icon: RESEARCH_FUND_PAGE_ICONS.approvalRecords, tone: "emerald" },
  announcements: { icon: RESEARCH_FUND_PAGE_ICONS.announcements, tone: "amber" },
  projects: { icon: RESEARCH_FUND_PAGE_ICONS.projects, tone: "violet" },
  "dept-review": { icon: RESEARCH_FUND_PAGE_ICONS.departmentReview, tone: "rose" },
});

export const ADMIN_MENU_PRESENTATION = Object.freeze({
  dashboard: { icon: RESEARCH_FUND_PAGE_ICONS.dashboard, tone: "blue" },
  "research-dashboard": { icon: RESEARCH_FUND_PAGE_ICONS.researchDashboard, tone: "violet" },
  "research-fund": { icon: RESEARCH_FUND_PAGE_ICONS.researchFund, tone: "emerald" },
  "promotion-fund": { icon: RESEARCH_FUND_PAGE_ICONS.promotionFund, tone: "amber" },
  "applications-list": { icon: RESEARCH_FUND_PAGE_ICONS.adminApplications, tone: "sky" },
  "scopus-research-search": { icon: RESEARCH_FUND_PAGE_ICONS.researchSearch, tone: "violet" },
  "scopus-benchmark": { icon: RESEARCH_FUND_PAGE_ICONS.scopusBenchmark, tone: "indigo" },
  "fund-settings": { icon: RESEARCH_FUND_PAGE_ICONS.fundSettings, tone: "slate" },
  projects: { icon: RESEARCH_FUND_PAGE_ICONS.projects, tone: "teal" },
  "approval-records": { icon: RESEARCH_FUND_PAGE_ICONS.approvalRecords, tone: "emerald" },
  "import-export": { icon: RESEARCH_FUND_PAGE_ICONS.importExport, tone: "sky" },
  "academic-imports": { icon: RESEARCH_FUND_PAGE_ICONS.academicImports, tone: "violet" },
  "access-control": { icon: RESEARCH_FUND_PAGE_ICONS.accessControl, tone: "rose" },
});
