import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Anuphan } from "next/font/google";
import 'flowbite';
import 'flowbite/dist/flowbite.css';

const anuphan = Anuphan({
  subsets: ["thai"],
  variable: "--font-anuphan",
  weight: ["400", "700"], // เพิ่มได้ตามต้องการ
  display: "swap",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  font-raleway`}
      
      suppressHydrationWarning 
      >
        {children}
      </body>
    </html>
  );
}
